### PR TITLE
Add French, British, Dutch, and Finnish dependencies

### PR DESCRIPTION
**Pull request by ucarion**
Though I don't know in practice whether these codes are used by locals of these areas, in this PR I've added the ISO 3166 country codes of dependent territories of states subject to the GDPR.

I've also added French overseas departments (DOM), which aren't formally overseas _territories_ (technically they're just as much legally France as Corsica is), but nonetheless have their own ISO 3166 codes and use different locales.

Taken from: https://en.wikipedia.org/wiki/Dependent_territory

Of course: IANAL!

### CODE REVIEW

**Comment by ucarion** [comment]
@nettofarah I'm not sure I understand what sort of grouping you're talking about. Would we group country codes by the sovereign EU member who governs it?

**Comment by ucarion** [comment]
Also: I'm a little nervous about us having to make political statements in code. I mean sure, it's not like we have to decide whether _Palestine_ is part of some other country or some other really explosive question, but some of these categorizations of "master-dependency" are somewhat contentious subjects to locals. Just a thought.

**Comment by nettofarah** [comment]
ohh, I just realized I wasn't super clear.
Let me re-phrase.

I was thinking we could something like this.

- rename `countryCodes` to `onshoreCountryCodes`

```javascript
var onshoreCountryCodes = {
  BE: 'Belgium',
  EL: 'Greece'
  ...
}

var dependentTerritories = {
  AW: 'Aruba',
  CW: 'Curacao',
  SX: 'Sint Maarten'
  ...
}

var overseasDependencies = {
  RE: 'Reunion',
  GP: 'Guadeloupe',
  MQ: 'Martinique',
  GF: 'French Guiana'
  ...
}
```

and then re-write `inEULocale` to return something like this:
```javascript
return !!onshoreCountryCodes[code.toUpperCase()] || !!dependentTerritories[code.toUpperCase()] || !!overseasDependencies[code.toUpperCase()]
```

Do you think those variable names make sense?

**Comment by nettofarah** [comment]
Happy to just scrap this idea if you think this could become a point of contention :)

**Comment by jfmaggie** [comment]
@nettofarah Sure! I would love to follow up this idea. :)

**Comment by ucarion** [comment]
I guess I don't see what we're gaining from categorizing things that way. If anything, it might encourage people to try to only look at countries that are physically on the continent of Europe? But that's not what the EU is.

Also, I can say for sure that for _French_ people, the question of whether Guadeloupe "is just France" or some separate thing is not some trivial matter:

https://en.wikipedia.org/wiki/2009_French_Caribbean_general_strikes

So I think Segment should avoid commenting on the subject, just as we would avoid commenting on the political status of Taiwan. Unless there's a strong compelling reason to take a stance, which I'm not sure I see here.

**Comment by ucarion** [comment]
But I also don't want to bikeshed. So either way is fine by me. :)

**Comment by nettofarah** [comment]
Totally fine! I want to make sure we're doing the right thing. And I think your argument is 1000% valid.

Thanks again and let's ship this!

**Pull request merged**
